"""empty message

Revision ID: 084c639211f7
Revises: a541a4b58f05
Create Date: 2024-04-15 22:23:41.853225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084c639211f7'
down_revision = 'a541a4b58f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
